import "primereact/resources/themes/lara-light-blue/theme.css";
import "primereact/resources/primereact.min.css";
import "./globals.css";

import type { Metadata } from "next";
import { interVariable, dmsansVariable } from "./fonts";
import { Providers } from "./providers";

import Navbar from "./components/navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Ecom X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html suppressHydrationWarning lang="en">
        <body className={`${interVariable} ${dmsansVariable} antialiased`}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
